services:
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        env_file: .env
        environment:
            - AUTO_UPDATE=true
        volumes:
            - /var/lib/docker/volumes/jacket_data/_data:/config
            - /var/lib/docker/volumes/screentv_downloads/_data:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        env_file: .env
        environment:
            - TRANSMISSION_WEB_HOME=/combustion-release/
        volumes:
            - /var/lib/docker/volumes/transmission_data/_data:/config
            - /var/lib/docker/volumes/screentv_downloads/_data:/downloads
            - /var/lib/docker/volumes/screentv_watch/_data:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        env_file: .env
        volumes:
            - /var/lib/docker/volumes/radarr_data/_data:/config
            - /var/lib/docker/volumes/screentv_movies/_data:/movies #optional
            - /var/lib/docker/volumes/screentv_downloads/_data:/downloads #optional
        ports:
            - 7878:7878
        restart: unless-stopped
