services:
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
            - TZ=Europe/Athens
            - PUID=1000
            - PGID=1000
            - AUTO_UPDATE=true
        volumes:
            - jackett_config:/config
            - downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        environment:
            - TZ=Europe/Athens
            - PUID=1000
            - PGID=1000
            - TRANSMISSION_WEB_HOME=/combustion-release/
        volumes:
            - transmission_config:/config
            - downloads:/downloads
            - watch:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        privileged: true
        environment:
            - TZ=Europe/Athens
            - PUID=1000
            - PGID=1000
        volumes:
            - radarr_config:/config
            - movies:/movies
            - downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    nzbget:
        image: ghcr.io/linuxserver/nzbget
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - nzb_config:/config
            - downloads:/downloads
        ports:
            - 6789:6789
        restart: unless-stopped
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Athens
        volumes:
            - sonnar_config:/config
            - tv_series:/tv #optional
            - downloads:/downloads #optional
        ports:
            - 8989:8989
        restart: unless-stopped
    bazarr:
        image: ghcr.io/linuxserver/bazarr
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Athens
        volumes:
            - bazarr_config:/config
            - movies:/moviesx
            - tv_series:/tv
        ports:
            - 6767:6767
        restart: unless-stopped
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Athens
            - VERSION=docker
        volumes:
            - plex_config:/config
            - transcode:/transcode
            - tv_series:/tv
            - movies:/movies
        ports:
            - 32400:32400/tcp
        restart: unless-stopped
volumes:
    nzb_config:
    jackett_config:
    radarr_config:
    sonnar_config:
    bazarr_config:
    plex_config:
    transmission_config:
    tv_series:
    movies:
    downloads:
    watch:
    transcode:
